version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_sessions_app
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest_sessions_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - '5050:80'
    depends_on:
      - db
